app/blueprints/auth.py
from urllib.parse import urljoin
from urllib.parse import urlparse

from app import db
from app.blueprints.email import send_password_reset_email
from app.forms import LoginForm
from app.forms import RegistrationForm
from app.forms import ResetPasswordForm
from app.forms import ResetPasswordRequestForm
from app.models import User
from flask import abort
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_login import current_user
from flask_login import login_required
from flask_login import login_user
from flask_login import logout_user

bp = Blueprint("auth", __name__, url_prefix="/auth")


def _is_safe_url(target):
    host_url = urlparse(request.host_url)
    next_url = urlparse(urljoin(request.host_url, target))
    return next_url.scheme in ("http", "https") and host_url.netloc == next_url.netloc


@bp.route("/register/", methods=["GET", "POST"])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("You have been registered!")
        return redirect(url_for("auth.login"))
    return render_template("auth/register.html", form=form)


@bp.route("/login/", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in")
        return redirect(url_for("homepage.index"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash("Invalid username or password")
            return redirect(url_for("auth.login"))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get("next")
        if not _is_safe_url(next_page):
            return abort(400)
        return redirect(next_page or url_for("homepage.index"))
    return render_template("auth/login.html", form=form)


@bp.route("/logout/")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))


@bp.route("/recover/", methods=["GET", "POST"])
def reset_password_request():
    form = ResetPasswordRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_password_reset_email(user)
        flash("Check your email for the instructions to reset your password")
    return render_template("auth/password_reset_request.html", form=form)


@bp.route("/reset/<token>/", methods=["GET", "POST"])
def reset_password(token):
    user = User.verify_reset_password_token(token)
    if not user:
        flash("Invalid recovery token")
        return redirect(url_for("homepage.index"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.set_password(form.password.data)
        db.session.commit()
        flash("Your password has been reset.")
        return redirect(url_for("homepage.index"))
    return render_template("email/password_reset_form.html", form=form)

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://kit.fontawesome.com/fe049644c5.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
                         integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
                                                            crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <title>
    {% block title %}{% endblock %}
    {% if current_user.is_authenticated %}
    - {{ current_user.username }}
    {% endif %}
  </title>
</head>

<body>
  <!-- navbar -->
  {% include 'navbar.html' %}
  <!-- main body container -->
  <div class="container-fluid">
    <!-- flash messages -->
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-info mt-4" role="alert">{{ message }}</div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% if current_user.is_authenticated %}
    <!-- task progress feedback -->
    {% with tasks = current_user.get_tasks_in_progress() %}
    {% if tasks %}
    {% for task in tasks %}
    <div class="alert alert-success" role="alert">
      <span id="{{ task.id }}-progress">Fetching task progress...</span>
      <script>{% include 'js/task-progress.js' %}</script>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% endif %}
    <!-- page content -->
    {% block app_content %}{% endblock %}
    <!-- footer -->
    {% include 'footer.html' %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
          integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
          crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
          integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
          crossorigin="anonymous"></script>
</body>

app/templates/footer.html
<div class="row">
  <footer class="footer pb-3" name="contato" id="contato">
    <div class="container">
      <div class="row">
        <div class="col-md-5">
          <h5><i class="fas fa-tv"></i> My-App</h5>
          <div class="row">
            <div class="col-4 col-lg-6">
              <ul class="list-unstyled">
                <li><a href="">Products</a></li>
                <li><a href="">Team</a></li>
                <li><a href="">Help</a></li>
              </ul>
            </div>
            <div class="col-8 col-lg-6">
              <ul class="list-unstyled">
                <li class="footer-text">mycompany@mydomain.com.br</li>
                <li class="footer-text">Info: xx.xxx.xxx/0001-xx</li>
                <li class="footer-text">(00) 1234-4567<i class="fab fa-whatsapp "></i></li>
              </ul>
            </div>
          </div>
          <ul class="nav">
            <li class="nav-item"><a href="#" class="nav-link pl-0"><i class="fa fa-facebook fa-lg"></i></a></li>
            <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-twitter fa-lg"></i></a>
            </li>
            <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-instagram fa-lg"></i></a>
            </li>
          </ul>
          <br>
        </div>
      </div>
    </div>
  </footer>
</div>

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-white py-3 shadow-sm">
  <div class="container">
    <a href="{{ url_for('homepage.index') }}"
       class="navbar-brand"><b>App</b>
    </a>
    <button type="button" data-toggle="collapse"
                          data-target="#navbarSupportedContent"
                          aria-controls="navbarSupportedContent"
                          aria-expanded="false"
                          aria-label="Toggle navigation"
                          class="navbar-toggler">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navbarSupportedContent" class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('homepage.index') }}">Home <span
                              class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
          <a id="navbarDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                                                                               aria-expanded="false" class="nav-link dropdown-toggle">Dropdown</a>
          <div aria-labelledby="navbarDropdown" class="dropdown-menu">
            <a href="#" class="dropdown-item">Action</a><a href="#" class="dropdown-item">Another
              action</a>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item">Something else here</a>
          </div>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.login') }}">Sign In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.register') }}">Sign Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.reset_password_request') }}">Forgot Your Password?</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>